### ISSUE TITLE
Outdented too far

### ISSUE THREAD

**Issue by chengguangnan** [threedaymonk/htmlbeautifier#18]
Hello, thank you for the gem. 

A minor issue in my usage, the "Outdented too far" exception. In my case, I don't really have anything else to do if it's incorrectly outdented. So I would just ignore it. 

```
#      raise "Outdented too far" if @level < 0
      @level = 0 if @level < 0
```

**Comment by threedaymonk** [comment]
That seems reasonable. I think what I'll do is:

* add a warning mode (`-w` perhaps)
* write a warning to `stderr` if warnings are enabled
* clamp the indentation level if it drops below zero
