### ISSUE TITLE
[ST2, Windows 7,x 64] Error: Invalid output. Check your interpreter settings

### ISSUE THREAD

**Issue by Javix** [threedaymonk/htmlbeautifier#19]
I installed the package in SublimeText2 on Windws 7, 64 bits.
I also installed the htmlbeautifier gem (https://github.com/threedaymonk/htmlbeautifier), then modified User settings in ST2 as follows as it was suggested in your README file:
```
{
    // Would you prefer a tab or two spaces to represent a tab
    // The default is two spaces represented by 'space'
    // anything else will use one tab character
    "file_patterns": ["\\.html\\.erb", "\\.rb", "\\.rake", "Rakefile", "Gemfile"],
    "html_erb_patterns": ["\\.html\\.erb"],
    "run_on_save": false,
    "save_on_beautify": true,
    "ruby": "ruby"
}
```
When hitting `CTRL-ALT-k` I got the below error displayed in a popup:
```
Error: Invalid output. Check your interpreter settings
```
I have Ruby installed:
```
C:\Windows\system32>ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [x64-mingw32]
```
So the formatting does not work as needed. Any idea ? Thank you

**Comment by threedaymonk** [comment]
That's not *my* README file; I wrote the utility, but the SublimeText plug-in is [CraigWilliams/BeautifyRuby](https://github.com/CraigWilliams/BeautifyRuby). They might be able to help you.

**Comment by Javix** [comment]
Oups, I'was mistaken, didn't check the address, sorry for that :)
