### ISSUE TITLE
case without matcher

### ISSUE THREAD

**Issue by zerocool4u2** [threedaymonk/htmlbeautifier#33]
It's not a mayor issue, but the class: "something" notation it's not supported, it is perceived as a class definition instead of a symbol definition so mess the indentation

```ruby
f.inputs Phone.model_name.human.pluralize do
			f.has_many :phones, allow_destroy: true, heading: nil do |phone|
				phone.input :area_code_id, as: :select, collection: AreaCode.all.order(:area_code).pluck(:area_code, :id), wrapper_html: { class: "phone_area_code_wrapper" }
																																			 phone.input :phone_number, wrapper_html: { class: "phone_phone_number_wrapper" }
																																														end
																																														end
																																														f.actions
																																														end
````

like i say, it's not a mayor issue, the :class => "" notation works fine  and is rare to have this kind of definitions in .rb files anyway(active_admin), regards!

**Comment by zerocool4u2** [comment]
not the best solution, but works for me, not really sure if there are other cases to avoid look for a general solution and the most important, class: should be a valid scenario for definition of a class? really don't know if there are some cases with this particular expression
```ruby
#(module|class[^:]|def)
  ruby.add_matcher(:standard,
                   /((#{start_statement_boundary}(module|class[^:]|def))|#{pre_keyword_boundary}do)\b/,
                   /(((^|;|\s)end)|#{continue_statement_boundary}(rescue|ensure))\b/,
                   :nest_except => [:double_quote, :regex, :backtick])
```

**Comment by threedaymonk** [comment]
I'm puzzled. What is this `ruby.add_matcher` syntax from? It's not part of this library!

**Comment by zerocool4u2** [comment]
really sorry!!! i'm working on this and other library at the same time, wrong tab, regards!
