### ISSUE TITLE
Where to put the "In your code" code?

### ISSUE THREAD

**Issue by atstockland** [threedaymonk/htmlbeautifier#37]
The REAME simply states "In your code" for installing the gem.  I have tried putting the suggested code in 3 different locations, with no success in installing this gem.  Where should I put "require 'htmlbeautifier'" and where should I put "beautiful = HtmlBeautifier.beautify(messy)"?  Is "messy" a variable I am supposed to set?  Thanks!

**Comment by threedaymonk** [comment]
This is the second issue you've opened. It looks like you're not very familiar with Ruby. Unfortunately, I'm not able to help you to learn Ruby and its ecosystem, though I'm happy to assist with more specific problems related to this library.

**Comment by atstockland** [comment]
!Thanks for the help and clarification on installing this gem.
