### ISSUE TITLE
Is there a way to specify file encoding?

### ISSUE THREAD

**Issue by izaera** [threedaymonk/htmlbeautifier#40]
Hi there:

I'm using htmlbeautifier and it works great (good job 👍 ), but I would like to know if there's a way to specify file encoding for .erb files because htmlbeautifier complains about:

> invalid byte sequence in US-ASCII on line 1

This is because I use unicode glyphs as icons and the beautifier fails to understand them.

Thanks in advance,
Ivan Zaera

**Comment by threedaymonk** [comment]
It should (and, as far as I 'm aware, does) support UTF-8. Can you give me some more information?

* The Ruby version you're using.
* Your locale settings (the output of `env | grep ^LC_`).
* A minimal sample document that demonstrates the problem.

Thanks!

**Comment by izaera** [comment]
Oops, that may be the problem: I'm running htmlbeautifier from Atom on Mac and it seems that I have a pretty bare environment with no LC_ or LANG variables at all.

Let me investigate it more and I'll come back with more data. I'll try to reproduce it from the command line.

BTW, thanks for the fast reply :-).

**Comment by izaera** [comment]
It seems to work from command line, so I guess it is a problem in the Atom plugin side. I'll further investigate it until I can fix it. I'll tell you after about my findings so that you can close this bug and in case it may be useful to someone having the same problem (or close it now if you want and I'll add the comment later, whatever you prefer :-) ).

Thanks for the help, again.

**Comment by izaera** [comment]
OK, I close it.

After much investigation, I have reinstalled the gem and the problem disappeared  :-(. I did this before (some time ago) and it kept failing but this time it has worked.

Sorry and thanks for the hint.
