### ISSUE TITLE
Support for erb formatting in vscode?

### ISSUE THREAD

**Issue by Neo42** [threedaymonk/htmlbeautifier#49]
How can I use htmlbeautifier for erb formatting in vscode?
I use rufo for rb file formatting in vscode, but haven't got any solutions for erb formatting.
Anyone can help out?

**Comment by aliariff** [comment]
Hey I just created a extension for that so that we can format it naturally using vscode provided API.
Feel free to try it.
https://marketplace.visualstudio.com/items?itemName=aliariff.vscode-erb-beautify

**Comment by mhatvan** [comment]
@aliariff I am trying to set it up right now but I can't seem to get it working with your extension, is this still valid in 2020 ?

**Comment by aliariff** [comment]
@mhatvan yes it is should be working, any error log message from your side?

**Comment by mhatvan** [comment]
I follow the steps in your readme, but it just doesn't format. 
files associations are set up and tried with *.html.erb or *.erb
With https://github.com/HookyQR/VSCodeBeautify it works and formats the file/ ignores ruby syntax in html

**Comment by aliariff** [comment]
@mhatvan 
Could you create an issue on my repo instead of this one? as it more related to the vscode plugin.
https://github.com/aliariff/vscode-erb-beautify

**Comment by Neo42** [comment]
Thx guys.
