### ISSUE TITLE
Could you make an option to let one empty row when there are multiple empty rows?

### ISSUE THREAD

**Issue by lichtamberg** [threedaymonk/htmlbeautifier#5]
Sometimes its really easier to read html code when there are some parts seperated with empty lines.. At the moment all empty lines get removed, but i would like to have at least one sometimes..

So it would be nice if there is an option which gives you the power to config like "reduce empty lines to 1"..

Do you understand what i mean?

**Comment by bbugh** [comment]
I'm using htmlbeautifier in conjunction with Sublime text and BeautifyRuby. Removing the extra newlines always is problematic. Is this still worthwhile to fix or have you adjusted it already?

**Comment by threedaymonk** [comment]
@bbugh I haven't fixed it yet, so yes, it would be worthwhile!

**Comment by kevin-jj** [comment]
+1

**Comment by abmohan** [comment]
@threedaymonk, are there plans to fix this? 

I understand this is open source, and appreciate your effort in creating and maintaining this. I'm in the unfortunate position of having to clean up some legacy code, and am relying heavily on htmlbeautify. It would be great to have this functioning. If you don't have the time to implement this feature, maybe you can point some of us in the right direction?

**Comment by threedaymonk** [comment]
@abmohan I'm afraid my answer is still the same: I think it would be a useful feature, and I'd welcome any contributions, but I probably won't implement it myself in the near future.

I think the simplest approach would be to add a multi-line matching expression [above `:new_line` in `html_parser.rb`](https://github.com/threedaymonk/htmlbeautifier/blob/2c9e54ab5d7da69afae4a0d5a15bc772becc8732/lib/htmlbeautifier/html_parser.rb#L48-L49) and to add a method in `builder.rb` that emits a new line *and* sets `@new_line = true`, but I haven't tried it.

**Comment by mkozono** [comment]
This option was added in #43

**Comment by mtomov** [comment]
So after #43 was merged, is this now closed, or we are waiting for a version release to close it and be able to use the feature?

Thanks a lot for implementing it! It is indeed a very useful one.

**Comment by mkozono** [comment]
@mtomov Looks like the feature should be available in the latest release. Yeah this probably should be closed.

& you're welcome! 🙂

**Comment by mtomov** [comment]
Ah, ok, thanks! ..was trying to use it with the Sublime plugin [BeautifyRuby](https://github.com/CraigWilliams/BeautifyRuby) and it didn't work right away, but just looked at the code, and it seems like the default `preserve_empty_lines` config has remained at `0`. 

Will have to see how to set it up maybe from the plugin, or if you are up for it I can submit a PR to change the default to `1`?

**Comment by mkozono** [comment]
@mtomov Yeah I think the plugin should set the value or expose the option :+1:
