### ISSUE TITLE
Lint mode?

### ISSUE THREAD

**Issue by samsondav** [threedaymonk/htmlbeautifier#52]
We want to lint our .html.erb files for valid HTML as a CI check. Can this libary do it?

**Comment by mweitzel** [comment]
Would a PR be welcome for this? I have a branch implementing a naive version of this but wanted to check before adding polish for a PR.

**Comment by threedaymonk** [comment]
Yes, that sounds useful. Please do!

**Comment by threedaymonk** [comment]
Included in 1.4.0 thanks to @mweitzel
