### ISSUE TITLE
Retain intentional line breaks

### ISSUE THREAD

**Issue by simmerz** [threedaymonk/htmlbeautifier#63]
It would be great if there were an option to retain line breaks that the developer places in the file intentionally to make readability of the partial easier. For instance:

```erb
<% page_title! "Project: #{project.name}" %>

<main>
  <header>
...
```
which currently gets turned into
```erb
<% page_title! "Project: #{project.name}" %>
<main>
  <header>
...
```

**Comment by kelostrada** [comment]
You have an option to do that already - just use `keep_blank_lines: 1`
